# Generated by Django 2.2.5 on 2019-09-05 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('note', models.TextField(blank=True, max_length=150)),
                ('orders_count', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('country_code_alpha', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=30)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('province', models.CharField(blank=True, max_length=20)),
                ('province_code', models.CharField(blank=True, max_length=3)),
                ('zip_code', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
        ),
    ]
