# Generated by Django 2.2.5 on 2019-09-05 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('handle', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='%Y-%m-%d/collections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('handle', models.SlugField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('featured_image', models.ImageField(blank=True, upload_to='%Y-%m-%d/products/')),
                ('sku', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ManyToManyField(blank=True, limit_choices_to=5, to='store.Collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('handle', models.SlugField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('featured_image', models.ImageField(blank=True, upload_to='%Y-%m-%d/products/')),
                ('sku', models.CharField(blank=True, max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
