# Generated by Django 2.2.5 on 2019-09-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, to='store.Collection'),
        ),
    ]
