# Generated by Django 2.2.5 on 2019-09-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190905_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y-%m-%d/collections/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y-%m-%d/products/'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='uploads/%Y-%m-%d/products/'),
        ),
    ]
