# Generated by Django 2.2.5 on 2019-09-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_collection_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='variant',
            name='handle',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
