# Generated by Django 2.2.5 on 2019-09-05 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='local',
            new_name='locale',
        ),
    ]
