# Generated by Django 2.2.5 on 2019-09-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('handle', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True, max_length=150)),
                ('featured_image', models.ImageField(blank=True, upload_to='uploads/%Y-%m-%d/collections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(blank=True)),
            ],
        ),
    ]
