# Generated by Django 2.2.5 on 2019-09-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='featured_image',
            field=models.ImageField(blank=True, upload_to='%Y-%m-%d/collections/'),
        ),
    ]
