# Generated by Django 2.2.5 on 2019-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190907_0526'),
        ('cart', '0002_auto_20190908_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
