# Generated by Django 2.2.5 on 2019-09-09 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20190907_0526'),
        ('cart', '0003_auto_20190909_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='cart.CartItem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_ip',
            field=models.CharField(editable=False, max_length=14, unique=True),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product'),
        ),
    ]
